#include <iostream>
#include <fstream>
#include <string> 
#include "DecodeGlobal.h"
#include <vector>
#include <filesystem>
#include <ctime>

using namespace std;

 
namespace fs = std::filesystem;


int main(int argc, char* argv[]){
    bool man = false;
    
    if (man) {
        ifstream myFile;
        myFile.open("user (31).bin", ios::in | ios::binary);


        myFile.seekg(0, myFile.end);
        int filelength = myFile.tellg();
        myFile.seekg(0, myFile.beg);
 
        char* buffer = new char[filelength];

        myFile.read(buffer, filelength);

        unsigned char* bufferDec = reinterpret_cast<unsigned char*>(buffer);

        DecodeGlobal decoder = DecodeGlobal(bufferDec, filelength, argv[0]);

        decoder.decode();

        decoder.writeToDisk();

        std::cout << "Press any key to exit..." << std::endl;
        getchar();
        exit(0);
        return (0);
    }

    if(argv[1] == "-help" || argc == 1){
        std::cout<<"Help for Decoder\n";

        std::cout<< "With this decoder application you can decode Files generated by the Historiographer application.\n";
        std::cout<< "Usage: Decoder (filenames to decode)\n";
        std::cout<< "You can list multiple files to decode with one execution. After every decoded file there will be a pause where you can look at some statistics.\n";
        std::cout<< "This can be turned off by appending the '-autoaccept' tag.\n";
        exit(0);
        return 0;
    }

    if (argc < 2) {
        std::cout << "ERROR: Wrong amount of arguments!" << std::endl;
        exit(0);
        return 0;
    }

    bool autoaccept = false;
    
    for (int i = 1; i < argc; i++)
    {
        string name = argv[i];
        if(name =="-autoaccept"){
            autoaccept = true;
        }
        else
        {      
            ifstream myFile;
            myFile.open(name , ios::in | ios::binary);


            myFile.seekg(0, myFile.end);
            int filelength = myFile.tellg();
            myFile.seekg(0, myFile.beg);

            if(filelength >0){
                char* buffer = new char[filelength];

            myFile.read(buffer, filelength);

            unsigned char* bufferDec = reinterpret_cast<unsigned char*>(buffer);

            DecodeGlobal decoder = DecodeGlobal(bufferDec, filelength, argv[0]);

            decoder.decode();

            decoder.writeToDisk();

            if(!autoaccept){
                std::cout << "Press any key to continue with the next file..." << std::endl;
                getchar();
            }
        }
        }
        
    }    
    exit(0);
    return 0;
}
